<?php
declare(strict_types=1);

namespace AIdoforyou\StockMetadata\Services\AI;

use WP_Error;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class GeminiClient {

    private readonly array $api_keys;
    private readonly string $api_base;
    private readonly string $resolution;

    public function __construct() {
        $keys_arr = json_decode( (string) get_option( 'aidofy_meta_api_keys', '[]' ), true );
        $this->api_keys = is_array( $keys_arr ) ? array_values( array_filter( $keys_arr ) ) : [];

        $base = (string) get_option( 'aidofy_meta_gemini_api_base', '' );
        $this->api_base = ! empty( $base ) ? rtrim( $base, '/' ) : 'https://generativelanguage.googleapis.com';

        $this->resolution = (string) get_option( 'aidofy_meta_media_resolution', 'MEDIA_RESOLUTION_HIGH' );
    }

    public function get_keys_count(): int {
        return count( $this->api_keys );
    }

    private function execute_request( string $model_id, int $server_index, array $body ): array|WP_Error {
        $api_key = $this->api_keys[ $server_index ] ?? $this->api_keys[0];
        $url     = "{$this->api_base}/v1beta/models/{$model_id}:generateContent?key={$api_key}";
        
        $timeout_sec = min( (int) get_option( 'aidofy_meta_api_timeout', 85 ), 95 );
        $host_parsed = parse_url( $this->api_base, PHP_URL_HOST );

        if ( $this->resolution !== 'default' ) {
            $body['generationConfig']['mediaResolution'] = $this->resolution;
        }

        $args = array(
            'headers' => array( 'Content-Type' => 'application/json', 'Host' => is_string($host_parsed) ? $host_parsed : '' ),
            'body'    => wp_json_encode( $body ),
            'timeout' => $timeout_sec,
        );

        $response = wp_safe_remote_post( $url, $args );
        
        if ( is_wp_error( $response ) ) return $response;

        $http_code = wp_remote_retrieve_response_code( $response );
        $raw_body  = wp_remote_retrieve_body( $response );
        $data      = json_decode( $raw_body, true );
        
        if ( ! is_array( $data ) ) return new WP_Error( 'ai_error', "Non-JSON response from API.", array( 'http_code' => $http_code ) );
        if ( isset( $data['error'] ) ) return new WP_Error( 'gemini_error', $data['error']['message'], array( 'http_code' => $http_code ) );
        if ( $http_code >= 400 ) return new WP_Error( 'http_error', "HTTP Error {$http_code}", array( 'http_code' => $http_code ) );

        $text = $data['candidates'][0]['content']['parts'][0]['text'] ?? null;
        if ( $text === null ) {
            return new WP_Error( 'ai_error', 'No text generated by AI.', array( 'http_code' => 500 ) );
        }

        return array(
            'http_code' => $http_code,
            'content'   => $this->clean_json_markdown( (string) $text )
        );
    }

    private function clean_json_markdown( string $text ): string {
        $clean_text = trim( $text );
        $clean_text = preg_replace( '/^```(json)?|```$/im', '', $clean_text );
        $clean_text = preg_replace( '/[\x00-\x1F\x7F]/', ' ', $clean_text );
        return trim( preg_replace( '/,\s*([\]}])/m', '$1', (string) $clean_text ) );
    }

    public function analyze( string $model_id, int $server_index, string $system_instruction, string $text_input, string $user_context, string $base64_data, string $mime_type ): array|WP_Error {
        $schema = array(
            'type' => 'OBJECT',
            'properties' => array(
                'literal_visual_evidence'     => array( 'type' => 'STRING', 'description' => 'Audit and list strictly literal physical subjects, actions, and setting details visible in the asset.' ),
                'commercial_intent_and_vibe'  => array( 'type' => 'STRING', 'description' => 'Identify the primary buyer intent, overarching commercial concepts, lifestyle themes, and moods that give this asset commercial value.' ),
                'intellectual_property_sweep' => array( 'type' => 'STRING', 'description' => 'Identify any brands, logos, or IP that must be generalized.' ),
                'commercial_concept'          => array( 'type' => 'STRING', 'description' => 'A structured sentence seamlessly combining themes from commercial_intent_and_vibe as the overarching theme at the beginning, with objects from literal_visual_evidence. Include high-value commercial keywords.' ),
                'active_modules'              => array( 'type' => 'ARRAY', 'items' => array( 'type' => 'STRING' ), 'description' => 'List of IDs for rule modules that apply to this asset.' )
            ),
            'required' => array( 'literal_visual_evidence', 'commercial_intent_and_vibe', 'intellectual_property_sweep', 'commercial_concept', 'active_modules' )
        );

        $combined_text = $text_input ? "Asset Concept: " . $text_input : "Extract metadata.";
        if ( ! empty( $user_context ) ) $combined_text .= "\n\nAdditional Context: \"" . $user_context . "\".";

        $parts = array();
        if ( ! empty( $base64_data ) ) {
            $parts[] = array( 'inline_data' => array( 'mime_type' => $mime_type, 'data' => $base64_data ) );
        }
        $parts[] = array( 'text' => $combined_text );

        $body = array(
            'system_instruction' => array( 'parts' => array( array( 'text' => $system_instruction ) ) ),
            'generationConfig'   => array(
                'responseMimeType'   => 'application/json',
                'responseJsonSchema' => $schema,
                'maxOutputTokens'    => 1024
            ),
            'safetySettings' => array(
                array( 'category' => 'HARM_CATEGORY_HARASSMENT', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_HATE_SPEECH', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_DANGEROUS_CONTENT', 'threshold' => 'BLOCK_NONE' ),
            ),
            'contents' => array( array( 'parts' => $parts ) )
        );

        return $this->execute_request( $model_id, $server_index, $body );
    }

    public function generate( string $model_id, int $server_index, string $system_instruction, string $text_input, string $user_context, string $base64_data, string $mime_type, string $thinking_level ): array|WP_Error {
        // Updated Descriptions to force methodological explanations, not early drafting
        $schema = array(
            'type' => 'OBJECT',
            'properties' => array(
                'pre_generation_audit' => array(
                    'type' => 'OBJECT',
                    'description' => 'Complete this strategy plan FIRST to establish logical formatting rules before outputting the final metadata arrays.',
                    'properties' => array(
                        'ambiguity_safeguards' => array( 'type' => 'STRING', 'description' => 'Identify unclear visual elements that must not be guessed in keywords.' ),
                        'media_type_and_category_strategy' => array( 'type' => 'STRING', 'description' => 'Explain the reasoning for your Category selection. You MUST prioritize the overarching commercial intent/theme (e.g., Lifestyle, Business) over literal objects (e.g., Food, People).' ),
                        'title_strategy' => array( 'type' => 'STRING', 'description' => 'Explain the structural strategy for the title. Detail how you will order the concepts. DO NOT write the actual title here.' ),
                        'keyword_strategy' => array( 'type' => 'STRING', 'description' => 'Plan the keyword hierarchy. Explain how tiers will be distributed. DO NOT output the final comma-separated list here.' )
                    ),
                    'required' => array( 'ambiguity_safeguards', 'media_type_and_category_strategy', 'title_strategy', 'keyword_strategy' )
                ),
                'media_type' => array( 'type' => 'STRING', 'enum' => array( 'Photos', 'Illustrations' ) ),
                'category'   => array( 'type' => 'STRING', 'enum' => array( 'Animals', 'Buildings and Architecture', 'Business', 'Drinks', 'The Environment', 'States of Mind', 'Food', 'Graphic Resources', 'Hobbies and Leisure', 'Industry', 'Landscape', 'Lifestyle', 'People', 'Plants and Flowers', 'Culture and Religion', 'Science', 'Social Issues', 'Sports', 'Technology', 'Transport', 'Travel' ) ),
                'title'      => array( 'type' => 'STRING', 'description' => 'Execute the planned title_strategy.' ),
                'keywords'   => array( 'type' => 'STRING', 'description' => 'Execute the planned keyword_strategy. Return as a comma-separated string.' ),
            ),
            'required' => array( 'pre_generation_audit', 'media_type', 'category', 'title', 'keywords' )
        );

        $combined_text = $text_input ? "Asset Concept: " . $text_input : "Extract metadata.";
        if ( ! empty( $user_context ) ) $combined_text .= "\n\nAdditional Context: \"" . $user_context . "\".";

        $parts = array();
        if ( ! empty( $base64_data ) ) {
            $parts[] = array( 'inline_data' => array( 'mime_type' => $mime_type, 'data' => $base64_data ) );
        }
        $parts[] = array( 'text' => $combined_text );

        $body = array(
            'system_instruction' => array( 'parts' => array( array( 'text' => $system_instruction ) ) ),
            'generationConfig'   => array(
                'responseMimeType'   => 'application/json',
                'responseJsonSchema' => $schema,
                'maxOutputTokens'    => 4096
            ),
            'safetySettings' => array(
                array( 'category' => 'HARM_CATEGORY_HARASSMENT', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_HATE_SPEECH', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'threshold' => 'BLOCK_NONE' ),
                array( 'category' => 'HARM_CATEGORY_DANGEROUS_CONTENT', 'threshold' => 'BLOCK_NONE' ),
            ),
            'contents' => array( array( 'parts' => $parts ) )
        );

        if ( ! empty( $thinking_level ) ) $body['generationConfig']['thinkingConfig'] = array( 'thinkingLevel' => $thinking_level );

        return $this->execute_request( $model_id, $server_index, $body );
    }
}